name: Render R Markdown
on:
  push:
    branches:
      - main  # Remplacez par le nom de votre branche si ce n'est pas 'main'
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Install pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
          sudo dpkg -i pandoc-2.7.3-1-amd64.deb
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-
      - name: Install R dependencies
        run: |
          echo "install.packages('rmarkdown')" > install.R
          Rscript install.R
      - name: Render R Markdown files
        run: |
          echo "rmarkdown::render('Test_git.Rmd')" > render.R
          Rscript render.R
      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        with:
          name: HTML report
          path: Test_git_sortie.html  # Remplacez par le nom de votre fichier de sortie si ce n'est pas 'Test_git.html'
